<?php

namespace Bontekoe\CinemaBundle\Entity;

/**
 * CinemaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CinemaRepository extends \Doctrine\ORM\EntityRepository
{
}
