<?php

namespace Bontekoe\CinemaBundle\Entity;

/**
 * ShowschemaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShowschemaRepository extends \Doctrine\ORM\EntityRepository
{
}
